-- hsqldb grammar
create table DDL_VERSION (
	ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	VERSION_NUMBER varchar(100),
	UPDATE_TYPE varchar(100)
);

--ALTER TABLE DDL_VERSION ADD CONSTRAINT UNIQUE1 UNIQUE(VERSION_NUMBER,UPDATE_TYPE);

insert into DDL_VERSION (VERSION_NUMBER, UPDATE_TYPE) values ('1.0.0','create-ddl');